#jpa:
#  hibernate:
#    naming:
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    ddl-auto: none

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/auth/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin