

security:
  oauth2:
    client:
      client-id: movies-ui
      client-secret: pin
      user-authorization-uri: http://localhost:9191/auth/oauth/authorize
      access-token-uri: http://localhost:9191/auth/oauth/token
    resource:
      token-info-uri: http://localhost:9191/auth/oauth/check_token
      user-info-uri: http://localhost:9191/user/me

server:
  servlet:
    session:
      cookie:
        name: KSESSION

